### ISSUE TITLE
Token inválido ao tentar gerar um segredo com KeyRegeneration diferente do padrão.

### ISSUE THREAD

**Issue by p-samuel** [CarlosHe/otp#1]
Boa tarde Carlos, não sei se estou fazendo corretamente, mas ao tentar validar um token com um KeyRegeneration diferente do padrão, ocorre a exceção de token inválido. Abaixo anexei meu código. Você saber o que pode ser?

![image](https://user-images.githubusercontent.com/53358247/210260515-e34dbf6e-369c-4e4f-9d54-a8db9a1eeb2a.png)

Também tentei colocar a propriedade SetKeyRegeneration do terceiro método para ficar igual a do segundo método, mas não funcionou.

Acho que só ocorre quando os valores para a propriedade SetKeyRegeneration são muito pequenos.

**Comment by CarlosHe** [comment]
Olá, Samuel!

No terceiro método, você precisa passar o valor do key regeneration no método SetKeyRegeneration da classe TOTPValidator.

```pascal
  TOTPValidator.New(
    TOTPCalculator
      .New
      .SetSecret(FSecret)
  )
  .SetKeyRegeneration(5)
  .SetToken(FToken)
  .Validate;
```

**Comment by p-samuel** [comment]
Obrigado, funcionou @CarlosHe!  Agora não está mais ocorrendo exceção. Ainda tenho só mais uma dúvida. A propriedade SetKeyRegeneration é a responsável por dizer quanto tempo o token será válido em segundos (ex.: SetKeyRegeneration(50) = 50s)?  Se for, parece que não está obedecendo o valor que eu coloco nela. Fiz os seguintes testes:

| SetKeyRegeneration  | Tempo |
|----------------------|----------|
|  5                                 |  23s      |   
|  60                               |  5 min   |   
|  12                                |  55s      | 

Esse é o comportamento normal mesmo?

**Comment by CarlosHe** [comment]
Sim, super normal esse comportamento! Isso ocorre por conta do parâmetro do Window Size, que por default, é o valor 4.

Então, ele fica válido em uma janela do tempo do valor do ```KeyRegeneration + WindowSize * KeyRegeneration```

Por exemplo:
| Key Regeneration  | Window Size | Duration|
|---------------------|---------------|-------|
|  5                  |  4            |  25s  |   
|  12                 |  4            |  60s  | 
|  60                 |  4            |  300s | 

Se você quiser alterar o valor do Window Size, basta chamar o método SetWindowSize da classe TOTPValidator.

**Comment by p-samuel** [comment]
Certo. Obrigado pelas informações @CarlosHe!
